- name: レポジトリ追加
  become: true
  blockinfile:
    dest: /etc/yum.repos.d/mongodb.repo
    create: yes
    content: |
      [mongodb]
      name=MongoDB Repository
      baseurl=http://downloads-distro.mongodb.org/repo/redhat/os/x86_64/
      gpgcheck=0
      enabled=1
- name: インストール
  become: true
  yum: name=mongodb-org
- name: サービス起動
  become: true
  service:
    name: mongod
    state: started
    enabled: true
