---
driver:
  name: vagrant

provisioner:
  name: ansible_push
  playbook: devhub.yml

platforms:
  - name: centos-6.7
    driver:
      box: bento/centos-6.7

suites:
  - name: default
    provisioner:
      hosts: devhub
