---
driver:
  name: vagrant

provisioner:
  name: ansible_push
  playbook: devhub.yml
  chef_bootstrap_url: false
  require_chef_for_busser: false
  require_ruby_for_busser: true
verifier:
  ruby_bindir: '/usr/bin'

platforms:
  - name: centos-6.7
    driver:
      box: bento/centos-6.7

suites:
  - name: default
    provisioner:
      hosts: devhub
