- name: co
  become: true
  git:
    repo: https://github.com/volpe28v/DevHub.git
    dest: /usr/local/devhub
- name: build
  become: true
  npm:
    path: /usr/local/devhub
- name: create DevHub service script
  become: true
  command: initd-forever -a /usr/local/devhub/app.js -n devhub
  args:
    chdir: /etc/init.d
- name: make DevHub script executable
  become: true
  file:
    path: /etc/init.d/devhub
    mode: 0755
- name: start　devhub service
  become: true
  service:
    name: devhub
    # statusの結果がおかしくてstartedだと起動してくれない
    state: restarted
    enabled: true
